### PR TITLE
Add margin-top to tabs

### PR DESCRIPTION
**Pull request by kocisov**
Fix for #6

### CODE REVIEW

**Comment by jellebreuer** [comment]
Thanks! did this manually, works like a charm :)

**Comment by dpo** [comment]
Bump. I find that I need 15px or icons are clipped. Here's what I get with 15px:

screen shot 2017-08-22 at 17 05 53

and with 10px:

screen shot 2017-08-22 at 17 07 13

**Comment by kocisov** [comment]
So like, it goes up to another 10px every atom update 😄

**Comment by kocisov** [comment]
Closing in regards to #22

**Pull request closed without merging**
